print("Enter Integer value:")
a=int(input())
print(("Integer value is:",a))
print(type(a))
print("  ")
b=float(input("Enter float value: "))
print(("Float value is:",b))
print(type(b))
print("  ")
c=input("Enter character value: ")
print(("Character value is:",c))
print(type(c))